# Generated by Django 5.2.8 on 2025-11-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', '用户'), ('admin', '管理员')], default='user', max_length=20, verbose_name='角色'),
        ),
    ]
