# Generated by Django 5.2.8 on 2025-11-24 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('recommendation', '职位推荐'), ('chat', 'AI聊天'), ('analysis', '简历分析'), ('other', '其他')], default='other', max_length=50, verbose_name='调用类型')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='模型名称')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='输入Token数')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='输出Token数')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总Token数')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='响应时间(秒)')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='调用时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI调用日志',
                'verbose_name_plural': 'AI调用日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='users_aical_created_cda59e_idx'), models.Index(fields=['user', '-created_at'], name='users_aical_user_id_bfc9a8_idx'), models.Index(fields=['call_type', '-created_at'], name='users_aical_call_ty_fd40ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='访问路径')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='请求方法')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户访问日志',
                'verbose_name_plural': '用户访问日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='users_usera_created_1de132_idx'), models.Index(fields=['user', '-created_at'], name='users_usera_user_id_bf48b4_idx')],
            },
        ),
    ]
