# Generated by Django 5.2.8 on 2025-11-20 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='行业')),
                ('company_type', models.CharField(choices=[('民营', '民营'), ('国企', '国企'), ('外企', '外企'), ('上市公司', '上市公司'), ('创业公司', '创业公司'), ('其他', '其他')], default='其他', max_length=50, verbose_name='公司类型')),
                ('company_size', models.CharField(blank=True, choices=[('20人以下', '20人以下'), ('20-99人', '20-99人'), ('100-499人', '100-499人'), ('500-999人', '500-999人'), ('1000-9999人', '1000-9999人'), ('10000人以上', '10000人以上')], max_length=50, verbose_name='公司规模')),
                ('description', models.TextField(blank=True, verbose_name='公司简介')),
                ('website', models.URLField(blank=True, verbose_name='公司网站')),
                ('logo', models.URLField(blank=True, verbose_name='公司Logo')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='公司地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
            },
        ),
        migrations.CreateModel(
            name='JobCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
            ],
            options={
                'verbose_name': '职位收藏',
                'verbose_name_plural': '职位收藏',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='职位名称')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='区域')),
                ('salary_min', models.IntegerField(default=0, verbose_name='最低薪资')),
                ('salary_max', models.IntegerField(default=0, verbose_name='最高薪资')),
                ('salary_months', models.IntegerField(default=12, verbose_name='薪资月数')),
                ('education', models.CharField(choices=[('不限', '不限'), ('大专', '大专'), ('本科', '本科'), ('硕士', '硕士'), ('博士', '博士')], default='不限', max_length=20, verbose_name='学历要求')),
                ('experience', models.CharField(choices=[('不限', '不限'), ('1年以下', '1年以下'), ('1-3年', '1-3年'), ('3-5年', '3-5年'), ('5-10年', '5-10年'), ('10年以上', '10年以上')], default='不限', max_length=20, verbose_name='经验要求')),
                ('description', models.TextField(blank=True, verbose_name='职位描述')),
                ('requirements', models.TextField(blank=True, verbose_name='任职要求')),
                ('welfare', models.CharField(blank=True, max_length=500, verbose_name='福利待遇')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='技能标签')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='数据来源')),
                ('source_id', models.CharField(blank=True, max_length=100, verbose_name='来源ID')),
                ('source_url', models.URLField(blank=True, verbose_name='来源链接')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('viewed', '已查看'), ('interview', '邀请面试'), ('rejected', '不合适'), ('accepted', '已录用')], default='pending', max_length=20, verbose_name='状态')),
                ('cover_letter', models.TextField(blank=True, verbose_name='求职信')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'verbose_name': '职位申请',
                'verbose_name_plural': '职位申请',
            },
        ),
    ]
