# Generated by Django 5.2.8 on 2025-11-20 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('education', models.CharField(max_length=20, verbose_name='学历')),
                ('experience', models.CharField(max_length=20, verbose_name='经验')),
                ('industry', models.CharField(max_length=100, verbose_name='行业')),
                ('skills', models.JSONField(default=list, verbose_name='技能')),
                ('predicted_salary', models.FloatField(verbose_name='预测薪资')),
                ('salary_min', models.FloatField(null=True, verbose_name='薪资下限')),
                ('salary_max', models.FloatField(null=True, verbose_name='薪资上限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='预测时间')),
            ],
            options={
                'verbose_name': '薪资预测历史',
                'verbose_name_plural': '薪资预测历史',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', '查看'), ('click', '点击'), ('apply', '申请'), ('collect', '收藏'), ('share', '分享')], max_length=20, verbose_name='行为类型')),
                ('duration', models.IntegerField(default=0, verbose_name='停留时长(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='行为时间')),
            ],
            options={
                'verbose_name': '用户行为',
                'verbose_name_plural': '用户行为',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(verbose_name='匹配度')),
                ('is_clicked', models.BooleanField(default=False, verbose_name='是否点击')),
                ('is_applied', models.BooleanField(default=False, verbose_name='是否申请')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='推荐时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_history', to='jobs.job')),
            ],
            options={
                'verbose_name': '推荐历史',
                'verbose_name_plural': '推荐历史',
                'ordering': ['-created_at'],
            },
        ),
    ]
